---
parser: babel-eslint
extends: eslint:recommended
env:
  node: true
rules:
  semi:
  - 2
  - always
  quotes:
  - 2
  - single
  no-undef:
  - 0
  no-var:
  - 1
  no-unused-vars:
  - 2
  - varsIgnorePattern: "^ssml$"
  no-console:
  - 1
