---
service: the-real-donald-trump

provider:
  name: aws
  runtime: nodejs6.10

  stage: dev
  region: eu-west-1

package:
  exclude:
    - package.json

functions:
  alexa-skill:
    handler: index.handler
    events:
      - alexaSkill
